Pim4_FazendaUrbana.WEB/Controllers/FornecedorController.cs
using Microsoft.AspNetCore.Mvc;
using Pim4_FazendaUrbana.DATA.Models;
using Pim4_FazendaUrbana.DATA.Services;
using Pim4_FazendaUrbana.WEB.Filters;

namespace Pim4_FazendaUrbana.WEB.Controllers
{
    [PaginaSomenteAdmin]
    public class FornecedorController : Controller
    {
        private FornecedorService _fornecedorService = new FornecedorService();

        public IActionResult Index()
        {
            List<Fornecedor> _listFornecedor = _fornecedorService._repositoryFornecedor.SelecionarTodos();
            return View(_listFornecedor);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Fornecedor model)
        {
            if(ModelState.IsValid)
            {
                _fornecedorService._repositoryFornecedor.Incluir(model);
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Details(int id)
        {
            Fornecedor fornecedor= _fornecedorService._repositoryFornecedor.SelecionarPk(id);
            return View(fornecedor);
        }

        public ActionResult Edit(int id)
        {
            Fornecedor fornecedor = _fornecedorService._repositoryFornecedor.SelecionarPk(id);
            return View(fornecedor);
        }

        [HttpPost]
        public ActionResult Edit(Fornecedor model)
        {
            Fornecedor fornecedor = _fornecedorService._repositoryFornecedor.Alterar(model);

            int id = fornecedor.IdFornecedor;

            return RedirectToAction("Details", new { id });
        }

        public ActionResult Delete(int id)
        {
            _fornecedorService._repositoryFornecedor.Excluir(id);
            return RedirectToAction("Index");
        }

    }
}

Pim4_FazendaUrbana.WEB/Controllers/PedidoController.cs
using Microsoft.AspNetCore.Mvc;
using Pim4_FazendaUrbana.DATA.Interfaces;
using Pim4_FazendaUrbana.DATA.Repositories;
using Pim4_FazendaUrbana.WEB.Filters;

namespace Pim4_FazendaUrbana.WEB.Controllers
{
    [PaginaSomenteAdmin]
    public class PedidoController : Controller
    {
        private readonly IRepositoryPedido _pedidoRepository;
        private readonly IRepositoryItemPedido _itemPedidoRepository;
        private readonly IRepositoryProduto _produtoRepository;
        public PedidoController(IRepositoryPedido pedidoRepository, IRepositoryItemPedido itemPedidoRepository)
        {
            _pedidoRepository = pedidoRepository;
            _itemPedidoRepository = itemPedidoRepository;
        }

        public IActionResult Index()
        {
            // Obtém todos os pedidos
            var pedidos = _pedidoRepository.SelecionarTodos();
            return View(pedidos);
        }

        public IActionResult Detalhes(int id)
        {
            // Obtém o pedido pelo ID e inclui os itens relacionados
            var pedido = _pedidoRepository.SelecionarPk(id);

            if (pedido == null)
            {
                return NotFound();
            }

            pedido.Itens = _itemPedidoRepository
            .SelecionarTodos()
            .Where(i => i.IdPedido == id)
            .ToList();

            return PartialView("_DetalhesPedido", pedido);
        }
    }

}

Pim4_FazendaUrbana.WEB/Controllers/PlantacaoController.cs
using Microsoft.AspNetCore.Mvc;
using Pim4_FazendaUrbana.DATA.Models;
using Pim4_FazendaUrbana.DATA.Services;
using Pim4_FazendaUrbana.WEB.Filters;

namespace Pim4_FazendaUrbana.WEB.Controllers
{
    [PaginaSomenteAdmin]
    public class PlantacaoController : Controller
    {
        private PlantacaoService _plantacaoService = new PlantacaoService();

        public IActionResult Index()
        {
            List<Plantacao> _listPlantacao= _plantacaoService._repositoryPlantacao.SelecionarTodos();
            return View(_listPlantacao);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Plantacao model)
        {
            if (ModelState.IsValid)
            {
                _plantacaoService._repositoryPlantacao.Incluir(model);
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Details(int id)
        {
            Plantacao plantacao = _plantacaoService._repositoryPlantacao.SelecionarPk(id);
            return View(plantacao);
        }

        public ActionResult Edit(int id)
        {
            Plantacao plantacao = _plantacaoService._repositoryPlantacao.SelecionarPk(id);
            return View(plantacao);
        }

        [HttpPost]
        public ActionResult Edit(Plantacao model)
        {
            Plantacao plantacao = _plantacaoService._repositoryPlantacao.Alterar(model);

            int id = plantacao.IdPlantio;

            return RedirectToAction("Details", new { id });
        }

        public IActionResult Delete(int id)
        {
            _plantacaoService._repositoryPlantacao.Excluir(id);
            return RedirectToAction("Index");
        }

    }
}

Pim4_FazendaUrbana.WEB/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc;
using Pim4_FazendaUrbana.DATA.Models;
using Pim4_FazendaUrbana.DATA.Services;
using Pim4_FazendaUrbana.WEB.Filters;

namespace Pim4_FazendaUrbana.WEB.Controllers
{
    [PaginaSomenteAdmin]
    public class ProdutoController : Controller
    {
        private ProdutoService _produtoService = new ProdutoService();

        public IActionResult Index()
        {
            List<Produto> _listProduto= _produtoService._repositoryProduto.SelecionarTodos();
            return View(_listProduto);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Produto model)
        {
            if (ModelState.IsValid)
            {
                _produtoService._repositoryProduto.Incluir(model);
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Details(int id)
        {
            Produto produto = _produtoService._repositoryProduto.SelecionarPk(id);
            return View(produto);
        }

        public ActionResult Edit(int id)
        {
            Produto produto = _produtoService._repositoryProduto.SelecionarPk(id);
            return View(produto);
        }

        [HttpPost]
        public ActionResult Edit(Produto model)
        {
            Produto produto = _produtoService._repositoryProduto.Alterar(model);

            int id = produto.IdProduto;

            return RedirectToAction("Details", new { id });
        }

        public ActionResult Delete(int id) 
        {
            _produtoService._repositoryProduto.Excluir(id);
            return RedirectToAction("Index");
        }

    }
}

Pim4_FazendaUrbana.WEB/Views/Shared/Components/Menu/Default.cshtml
@using Pim4_FazendaUrbana.DATA.Models
@model LoginModel

<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fazenda Urbana</a>
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Principal</a>
        </li>
        
        @if (Model.Perfil == Pim4_FazendaUrbana.WEB.Enums.PerfilEnum.Admin || Model.Perfil == Pim4_FazendaUrbana.WEB.Enums.PerfilEnum.Gerente)
        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Funcionario" asp-action="Index">Funcionário</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Fornecedor" asp-action="Index">Fornecedor</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Plantacao" asp-action="Index">Plantio</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Estoque</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Pedido" asp-action="Index">Pedidos</a>
            </li>
        }
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Carrinho" asp-action="Index">Vendas</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Sair">Sair</a>
        </li>
        
    </ul>